//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club1()
        {
            this.Club_Fixtures = new HashSet<Club_Fixtures>();
            this.Club_Fixtures1 = new HashSet<Club_Fixtures>();
            this.Footballers = new HashSet<Footballer>();
        }
    
        public int Club_Id { get; set; }
        public Nullable<int> Club_Rank { get; set; }
        public string Club_Name { get; set; }
        public Nullable<int> Club_Points { get; set; }
        public Nullable<int> Goals_Against { get; set; }
        public Nullable<int> Total_Goals { get; set; }
        public string Stadium_Name { get; set; }
        public string ManagerName { get; set; }
        public string FoundationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Club_Fixtures> Club_Fixtures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Club_Fixtures> Club_Fixtures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Footballer> Footballers { get; set; }
    }
}
