//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club_Fixtures
    {
        public int Host_id { get; set; }
        public int Guest_Id { get; set; }
        public int Week_number { get; set; }
        public int Season_number { get; set; }
        public string Score { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual Week Week { get; set; }
    }
}
