//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fantasy_Player_Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fantasy_Player_Team()
        {
            this.Transfereds = new HashSet<Transfered>();
            this.Fantasy_League = new HashSet<Fantasy_League>();
            this.Footballers = new HashSet<Footballer>();
        }
    
        public string Player_Username { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public int Fantasy_Team_ID { get; set; }
        public string Team_Name { get; set; }
        public Nullable<int> Total_Value { get; set; }
        public Nullable<int> Team_Funds { get; set; }
        public Nullable<int> Total_Points { get; set; }
        public Nullable<int> Total_Transfers { get; set; }
        public Nullable<int> Overall_Rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfered> Transfereds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fantasy_League> Fantasy_League { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Footballer> Footballers { get; set; }
    }
}
