//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fantasy_League
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fantasy_League()
        {
            this.Fantasy_Player_Team = new HashSet<Fantasy_Player_Team>();
        }
    
        public int League_Id { get; set; }
        public string League_Name { get; set; }
        public string Country { get; set; }
        public Nullable<int> Total_Players { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fantasy_Player_Team> Fantasy_Player_Team { get; set; }
    }
}
