//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footballer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Footballer()
        {
            this.Transfereds = new HashSet<Transfered>();
            this.Unavailable_Player = new HashSet<Unavailable_Player>();
            this.Fantasy_Player_Team = new HashSet<Fantasy_Player_Team>();
        }
    
        public int Player_Id { get; set; }
        public Nullable<int> Club_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Poisition { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Goals { get; set; }
        public Nullable<int> Assists { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> CleanSheets { get; set; }
    
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfered> Transfereds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unavailable_Player> Unavailable_Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fantasy_Player_Team> Fantasy_Player_Team { get; set; }
    }
}
