//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasyEntities : DbContext
    {
        public FantasyEntities()
            : base("name=FantasyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Club_Fixtures> Club_Fixtures { get; set; }
        public virtual DbSet<Fantasy_League> Fantasy_League { get; set; }
        public virtual DbSet<Fantasy_Player_Team> Fantasy_Player_Team { get; set; }
        public virtual DbSet<Footballer> Footballers { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Transfered> Transfereds { get; set; }
        public virtual DbSet<Unavailable_Player> Unavailable_Player { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
    }
}
