//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfered
    {
        public int Player_ID { get; set; }
        public int Week_Number { get; set; }
        public int Season_Number { get; set; }
        public int Fantasy_Team_ID { get; set; }
        public string status { get; set; }
    
        public virtual Fantasy_Player_Team Fantasy_Player_Team { get; set; }
        public virtual Footballer Footballer { get; set; }
        public virtual Week Week { get; set; }
    }
}
